apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: github-releasediff
  description: get number of releases between two releases.
  tags:
    - golang
  annotations:
    github.com/project-slug:  BESTSELLER/github-releasediff
spec:
  type: service
  lifecycle: production
  owner: engineering-services
